# Generated by Django 5.1 on 2024-08-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('start_at', models.DateTimeField()),
                ('period', models.IntegerField(default=None)),
            ],
            options={
                'verbose_name': 'События',
                'verbose_name_plural': 'События',
                'db_table': 'events',
            },
        ),
    ]
