# Generated by Django 5.1 on 2024-08-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
    ]
