# Generated by Django 5.1 on 2024-08-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_events_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='period',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
