# Generated by Django 5.1 on 2024-08-26 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_events_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RENAME', 'Rename'), ('STOP', 'Stop'), ('DELETE', 'Delete')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.events')),
            ],
            options={
                'verbose_name': 'Изменение События',
                'verbose_name_plural': 'Изменения События',
                'db_table': 'events_changes',
            },
        ),
    ]
