# Generated by Django 5.1 on 2024-08-26 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_eventschanges_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschanges',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.events'),
        ),
    ]
